version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    command: gunicorn --bind 0.0.0.0:8000 src.main.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - web_network
      - web_db_network
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost:8000/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web_db_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin" ]



  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro
    depends_on:
      - web
    networks:
      - web_network
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  web_network:
    driver: bridge
  web_db_network:
    driver: bridge

volumes:
  db_data:
